name: Build and deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Branch to use
        type: string
        required: true
        default: main  
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          ref: ${{ inputs.BRANCH || "main" }}

      - name: Install, lint, build 🔧
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
